---
title: "Story Graphs"
output: html_notebook
---

This notebook is used for generating the story graphs.

Loading packages

```{r}

# pacman package makes it easy to install multiple packages
if (!require(pacman))
  install.packages("pacman")

# load some required packages
pacman::p_load('dplyr', 'tidyr', 'gapminder',
               'ggplot2',  'ggalt',
               'forcats', 'R.utils', 'png', 
               'grid', 'ggpubr', 'scales',
               'bbplot')

# load bbc plot packages. uncomment devtools install as needed
# install.packages('devtools')
devtools::install_github('bbc/bbplot')

```


# basic test for the plot package
```{r}
#Data for chart from gapminder package
line_df <- gapminder %>%
  filter(country == "Uganda") 

#Make plot
line <- ggplot(line_df, aes(x = year, y = lifeExp)) +
  geom_line(colour = "#808080", size = 3) +
  geom_hline(yintercept = 1, size = 1, colour="#333333") +
  bbc_style() +
  labs(title="Living longer",
       subtitle = "Life expectancy in Uganda 1952-2007")

print(line)
```

# basic bar chart
```{r}
#Prepare data
bar_df <- gapminder %>%
  filter(year == 2007 & continent == "Africa") %>%
  arrange(desc(lifeExp)) %>%
  head(5)

#Make plot
bars <- ggplot(bar_df, aes(x = country, y = lifeExp)) +
  geom_bar(stat="identity", 
           position="identity", 
           fill="#1380A1") +
  geom_hline(yintercept = 0, size = 1, colour="#333333") +
  bbc_style() +
  labs(title="Reunion is highest",
       subtitle = "Highest African life expectancy, 2007")
print(bars)
```

# makeing up an arbitrary bar chart
```{r}
employee <- c('John Doe','Peter Gynn','Jolie Hope')
salary <- c(21000, 23400, 26800)
startdate <- as.Date(c('2010-11-1','2008-3-25','2007-3-14'))
employ.data <- data.frame(employee, salary, startdate)

emp_bars <- ggplot(employ.data, aes(x = employee, y = salary)) +
  geom_bar(stat="identity", 
           position="identity", 
           fill="#1380A1") +
  geom_hline(yintercept = 0, size = 1, colour="#333333") +
  bbc_style() +
  labs(title="Title",
       subtitle = "Subtitle")
print(emp_bars)

```

